const specialties = [
  {
    id: 'pho-ha-noi',
    name: 'Phở Hà Nội',
    region: 'mien-bac',
    regionName: 'Miền Bắc',
    place: 'Hà Nội',
    image: 'https://pbs.twimg.com/media/HQiVIqabYAAQLRr?format=jpg&name=large',
    description: 'Nước dùng trong veo, ngọt thanh từ xương bò hòa cùng bánh phở mềm và hương thơm của rau gia vị.',
    story: 'Phở là món quà sáng thân thuộc của Hà Nội. Một bát phở đúng điệu có nước dùng được ninh kỹ, thơm mùi quế hồi, ăn cùng thịt bò thái mỏng và hành hoa.',
    ingredients: ['Bánh phở tươi', 'Thịt bò', 'Xương bò', 'Quế, hồi', 'Hành, rau thơm', 'Chanh, ớt'],
    rating: 4.9
  },
  {
    id: 'bun-cha',
    name: 'Bún chả Hà Nội',
    region: 'mien-bac',
    regionName: 'Miền Bắc',
    place: 'Hà Nội',
    image: 'https://pbs.twimg.com/media/HQiVNdlawAAGPSf?format=jpg&name=large',
    description: 'Bún tươi ăn kèm chả nướng thơm lừng, nước chấm chua ngọt và rau sống.',
    story: 'Mùi chả nướng trên than hồng là một phần ký ức phố cổ. Vị béo của thịt, thanh của bún và đậm đà của nước chấm tạo nên sự cân bằng đặc trưng.',
    ingredients: ['Bún tươi', 'Thịt ba chỉ', 'Thịt xay', 'Nước mắm', 'Rau sống', 'Chanh, ớt'],
    rating: 4.8
  },
  {
    id: 'cha-ca-la-vong',
    name: 'Chả cá Lã Vọng',
    region: 'mien-bac',
    regionName: 'Miền Bắc',
    place: 'Hà Nội',
    image: 'https://pbs.twimg.com/media/HQiVMjUakAA0oy8?format=jpg&name=medium',
    description: 'Cá lăng ướp nghệ, thì là, áp chảo nóng hổi và dùng với bún, mắm tôm.',
    story: 'Món ăn lâu đời này gây ấn tượng bởi sắc vàng của nghệ và hương thì là bốc lên từ chảo nóng. Đây là trải nghiệm ẩm thực phố cổ khó quên.',
    ingredients: ['Cá lăng', 'Nghệ tươi', 'Thì là', 'Bún', 'Mắm tôm'],
    rating: 4.7
  },
  {
    id: 'banh-cuon',
    name: 'Bánh cuốn Thanh Trì',
    region: 'mien-bac',
    regionName: 'Miền Bắc',
    place: 'Hà Nội',
    image: 'https://pbs.twimg.com/media/HQiVJfPa8AAF-Ub?format=jpg&name=4096x4096',
    description: 'Lớp bánh mỏng mượt, nhân thịt mộc nhĩ, chấm nước mắm pha thanh nhẹ.',
    story: 'Bánh cuốn được tráng ngay khi khách gọi, giữ trọn độ mềm mịn của bột gạo. Chút hành phi vàng ruộm làm món ăn càng thêm quyến rũ.',
    ingredients: ['Bột gạo', 'Thịt heo', 'Mộc nhĩ', 'Hành phi', 'Nước mắm', 'Rau thơm', 'Chanh, ớt'],
    rating: 4.6
  },
  {
    id: 'bun-bo-hue',
    name: 'Bún bò Huế',
    region: 'mien-trung',
    regionName: 'Miền Trung',
    place: 'Huế',
    image: 'https://pbs.twimg.com/media/HQiVUQ1bsAEwjMe?format=jpg&name=medium',
    description: 'Sợi bún to, nước dùng cay thơm sả, giò heo và chả cua đậm vị cố đô.',
    story: 'Bún bò Huế mang nét nồng nàn của miền Trung: vị mắm ruốc sâu, ớt sa tế cay và hương sả đầy lôi cuốn.',
    ingredients: ['Bún sợi to', 'Bắp bò', 'Giò heo', 'Mắm ruốc', 'Sả, ớt'],
    rating: 4.9
  },
  {
    id: 'mi-quang',
    name: 'Mì Quảng',
    region: 'mien-trung',
    regionName: 'Miền Trung',
    place: 'Quảng Nam',
    image: 'https://pbs.twimg.com/media/HQiVV1Xa8AAISRD?format=jpg&name=large',
    description: 'Sợi mì vàng nghệ, nước nhân đậm đà, ăn kèm rau sống, đậu phộng và bánh tráng.',
    story: 'Không nhiều nước như các món bún khác, mì Quảng chinh phục thực khách bằng phần nhân cô đọng và rau sống tươi non của vùng đất Quảng.',
    ingredients: ['Mì gạo', 'Tôm, thịt', 'Nghệ', 'Đậu phộng', 'Bánh tráng'],
    rating: 4.8
  },
  {
    id: 'cao-lau',
    name: 'Cao lầu Hội An',
    region: 'mien-trung',
    regionName: 'Miền Trung',
    place: 'Hội An',
    image: 'https://pbs.twimg.com/media/HQiVR_vacAA0P-4?format=jpg&name=medium',
    description: 'Sợi cao lầu dai, thịt xá xíu, rau Trà Quế và tóp mỡ giòn tan.',
    story: 'Cao lầu là món ăn gắn chặt với thương cảng Hội An xưa. Sợi mì đặc biệt, phần rau thơm và nước xíu ít nhưng đậm vị tạo nên dấu ấn riêng.',
    ingredients: ['Sợi cao lầu', 'Thịt xá xíu', 'Rau Trà Quế', 'Tóp mỡ', 'Nước xíu'],
    rating: 4.8
  },
  {
    id: 'com-hen',
    name: 'Cơm hến',
    region: 'mien-trung',
    regionName: 'Miền Trung',
    place: 'Huế',
    image: 'https://pbs.twimg.com/media/HQiVRfRa0AAFkHo?format=png&name=900x900',
    description: 'Cơm nguội trộn hến xào, rau thơm, bắp chuối, đậu phộng và nước hến nóng.',
    story: 'Từ những nguyên liệu bình dị, người Huế tạo nên món cơm hến nhiều tầng vị: cay, mặn, thơm và giòn rụm.',
    ingredients: ['Cơm trắng', 'Hến', 'Rau thơm', 'Bắp chuối', 'Đậu phộng'],
    rating: 4.7
  },
  {
    id: 'banh-mi-sai-gon',
    name: 'Bánh mì Sài Gòn',
    region: 'mien-nam',
    regionName: 'Miền Nam',
    place: 'TP. Hồ Chí Minh',
    image: 'https://pbs.twimg.com/media/HQiVck3bMAALzVu?format=jpg&name=medium',
    description: 'Ổ bánh giòn rụm đầy ắp pate, thịt, đồ chua, rau thơm và nước sốt.',
    story: 'Bánh mì Sài Gòn là lựa chọn nhanh gọn nhưng luôn hào phóng hương vị. Lớp vỏ giòn, nhân phong phú và vị đồ chua tươi sáng.',
    ingredients: ['Bánh mì', 'Pate', 'Thịt nguội', 'Đồ chua', 'Rau ngò'],
    rating: 4.9
  },
  {
    id: 'hu-tieu-nam-vang',
    name: 'Hủ tiếu Nam Vang',
    region: 'mien-nam',
    regionName: 'Miền Nam',
    place: 'TP. Hồ Chí Minh',
    image: 'https://pbs.twimg.com/media/HQiVb-MagAAf7HK?format=jpg&name=large',
    description: 'Hủ tiếu dai mềm, nước dùng ngọt xương, đầy đặn tôm, thịt bằm và lòng heo.',
    story: 'Được người Sài Gòn yêu mến, hủ tiếu Nam Vang nổi bật bởi phần topping phong phú và nước dùng trong, ngọt dịu.',
    ingredients: ['Hủ tiếu', 'Tôm', 'Thịt bằm', 'Lòng heo', 'Hẹ'],
    rating: 4.8
  },
  {
    id: 'goi-cuon',
    name: 'Gỏi cuốn',
    region: 'mien-nam',
    regionName: 'Miền Nam',
    place: 'TP. Hồ Chí Minh',
    image: 'https://pbs.twimg.com/media/HQiVZ-TaUAAoPz3?format=jpg&name=large',
    description: 'Tôm thịt, bún và rau xanh cuốn trong bánh tráng, chấm tương đậu phộng.',
    story: 'Trong trẻo, tươi mát và cân bằng, gỏi cuốn là món khai vị thể hiện sự tinh tế của ẩm thực phương Nam.',
    ingredients: ['Bánh tráng', 'Tôm', 'Thịt ba chỉ', 'Bún', 'Rau sống'],
    rating: 4.7
  },
  {
    id: 'ca-kho-to',
    name: 'Cá kho tộ',
    region: 'mien-nam',
    regionName: 'Miền Nam',
    place: 'Cần Thơ',
    image: 'https://pbs.twimg.com/media/HQiVZb4bIAAPLeU?format=jpg&name=large',
    description: 'Cá kho trong niêu đất với nước màu óng ánh, vị mặn ngọt đặc trưng miền sông nước.',
    story: 'Niêu cá kho bốc khói bên mâm cơm trắng là hương vị gia đình thân thương của vùng đồng bằng sông Cửu Long.',
    ingredients: ['Cá lóc', 'Nước mắm', 'Nước dừa', 'Tiêu', 'Ớt'],
    rating: 4.6
  },
  {
    id: 'bun-ca-ro-dong',
    name: 'Bún cá Rô Đồng',
    region: 'mien-bac',
    regionName: 'Miền Bắc',
    place: 'Hải Dương',
    image: 'https://pbs.twimg.com/media/HQiVH58acAAGtqA?format=png&name=900x900',
    description: 'Bún cá rô đồng là một món ăn mộc mạc, đậm đà hương vị đồng quê đặc trưng của ẩm thực miền Bắc.',
    story: 'Món ăn này là sự hòa quyện hoàn hảo giữa nước dùng trong vắt, ngọt thanh được ninh cẩn thận từ xương cá, kết hợp cùng những sợi bún trắng mềm và phần thịt cá rô đồng ngọt chắc.',
    ingredients: ['Cá rô đồng tươi', 'Bún tươi', 'Rau cải', 'Hành hoa', 'Thì là', 'Ớt tươi', 'Chanh'],
    rating: 4.7
  },
  {
    id: 'ca-kho-lang-vu-dai',
    name: 'Cá kho Làng Vũ Đại',
    region: 'mien-bac',
    regionName: 'Miền Bắc',
    place: 'Hà Nam',
    image: 'https://pbs.twimg.com/media/HQiVHKvaEAAs9f9?format=jpg&name=large',
    description: 'Món ăn này được tuyển chọn từ những con cá trắm đen to, mình dày, kết hợp cùng thịt ba chỉ béo ngậy và các gia vị dân dã. Điểm làm nên linh hồn của món cá này là quá trình đun liên tục từ 12 đến 24 tiếng trong niêu đất trên ngọn lửa củi nhãn, tạo nên hương vị đậm đà, thơm lừng và màu sắc hấp dẫn.',
    story: 'Cá kho làng Vũ Đại là món đặc sản truyền thống trứ danh của tỉnh Hà Nam, nổi bật với sự kỳ công và hương vị cổ truyền đậm đà.',
    ingredients: ['Cá trắm đen tươi', 'Nước mắm', 'Nước dừa', 'Tiêu', 'Ớt', 'Gừng', 'Giềng', 'Nước cốt chanh', 'Nước cốt cua đồng'],
    rating: 4.8
  },
  {
    id: 'banh-bot-loc',
    name: 'Bánh bột lọc',
    region: 'mien-trung',
    regionName: 'Miền Trung',
    place: 'Huế',
    image: 'https://pbs.twimg.com/media/HQiVQY5agAA7YiZ?format=png&name=900x900',
    description: 'Bánh có thể được gói gọn gàng trong lá chuối rồi mang hấp, hoặc luộc trần vớt ra đĩa. Khi chín, vỏ bánh chuyển sang trạng thái trong suốt, dẻo dai, để lộ phần nhân đỏ au hấp dẫn bên trong.',
    story: 'Bánh bột lọc là một thức bánh đặc sản nức tiếng của xứ Huế, chinh phục thực khách bởi vẻ ngoài mộc mạc nhưng lại mang hương vị dai ngon khó cưỡng.',
    ingredients: ['Bột năng', 'Tôm', 'Thịt ba chỉ', 'Mộc nhĩ', 'Hành phi', 'Nước mắm', 'Rau thơm'],
    rating: 4.5
  },
  {
    id: 'banh-nam',
    name: 'Bánh nậm',
    region: 'mien-trung',
    regionName: 'Miền Trung',
    place: 'Huế',
    image: 'https://pbs.twimg.com/media/HQiVQ8zbYAAhKpj?format=jpg&name=large',
    description: 'Điểm nhấn trên nền bột trắng ngần ấy là phần nhân tôm thịt băm nhuyễn, được nêm nếm đậm đà và xào lên tơi xốp, mang màu cam đỏ vô cùng bắt mắt.',
    story: 'Bánh nậm là một món bánh truyền thống mang đậm bản sắc và sự tinh tế của ẩm thực xứ Huế. Bánh được làm từ bột gạo tẻ mịn màng, tráng một lớp mỏng dẹt trên mặt lá chuối xanh ngắt.',
    ingredients: ['Bột gạo', 'tôm băm', 'thịt heo băm', 'lá chuối', 'hành phi', 'nước mắm', 'rau thơm'],
    rating: 4.6
  },
  {
    id: 'ca-loc-nuong-trui',
    name: 'Cá lóc nướng trui',
    region: 'mien-nam',
    regionName: 'Miền Nam',
    place: 'Tây Nam Bộ',
    image: 'https://pbs.twimg.com/media/HQiVY50bsAAf_Bb?format=jpg&name=medium',
    description: 'Cá lóc đồng tươi rói vừa bắt lên sẽ được xiên dọc bằng một nhánh tre tươi, cắm xuống đất, phủ kín rơm rạ khô rồi châm lửa nướng. Khi cá chín, phần da cháy xém, thịt bên trong vẫn giữ được độ ngọt và mềm, ăn kèm với rau sống, bún và nước mắm chua ngọt.',
    story: 'Cá lóc nướng trui là món ăn dân dã, mang đậm cốt cách phóng khoáng và hương vị nguyên bản của vùng miền Tây sông nước.',
    ingredients: ['Cá lóc đồng', 'rơm khô', 'rau sống', 'bánh tráng', 'nước mắm me', 'ớt', 'tỏi', 'đường', 'chanh'],
    rating: 4.8
  },
  {
    id: 'vit-nau-chao',
    name: 'Vịt nấu chao',
    region: 'mien-nam',
    regionName: 'Miền Nam',
    place: 'Cần Thơ',
    image: 'https://pbs.twimg.com/media/HQiVYSGaMAAFLtx?format=jpg&name=medium',
    description: 'Linh hồn của món ăn nằm ở sự kết hợp hoàn hảo giữa thịt vịt săn chắc được sơ chế kỹ lưỡng, tẩm ướp đậm đà cùng "chao" loại đậu hũ lên men mang mùi thơm nồng nàn và vị béo mặn mộc mạc.',
    story: 'Vịt nấu chao là một món ăn đặc sản trứ danh của vùng sông nước miền Tây Nam Bộ, mang hương vị đậm đà, béo ngậy và vô cùng đặc trưng.',
    ingredients: ['Thịt vịt', 'chao trắng', 'chao đỏ', 'khoai môn', 'nước dừa tươi', 'nấm rơm', 'hành tím', 'tỏi', 'ớt', 'đường', 'tiêu', 'nước mắm', 'rau thơm'],
    rating: 4.8
  }
];
